# Site Info
title:              "rence"
description:        "a blog"
author_name:        "Lawrence Wang" # change this to your name
logo_url:           https://images.squarespace-cdn.com/content/5b39c0cb7c93273d7754f5cd/1532756167452-42P31FHET7OEXKMRZGN7/LW2mod1.png?content-type=image%2Fpng
# Site Settings
url:                https://law-wang.github.io # main url
baseurl:            
permalink:          /:title # Post permalink
timezone:           US/Pacific # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
